# Generated by Django 5.1.4 on 2025-01-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectuser",
            name="user_email",
        ),
    ]
