# Generated by Django 5.1.5 on 2025-01-20 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectuser",
            name="user_email",
        ),
    ]
