repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: [--line-length=88]

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.17.5
    hooks:
      - id: pylint
        name: pylint
        args: [--disable=R,C]
