# Generated by Django 5.1.4 on 2024-12-26 10:00

import django.db.models.deletion
import tasks.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('BACKLOG', 'Backlog'), ('RUNNING', 'Running'), ('DONE', 'Done')], default='PENDING', max_length=10)),
                ('deadline', models.DateTimeField(blank=True, null=True, validators=[tasks.validators.validate_deadline_in_future])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='TaskSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('PERFORMER', 'Performer'), ('SUBSCRIBER', 'Subscriber')], default='PERFORMER', max_length=10)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tasks.task')),
            ],
            options={
                'unique_together': {('task', 'user_id')},
            },
        ),
    ]
