name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  black:
    name: Run Black
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run Black
        run: black .

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Setup Docker
        uses: docker/setup-docker-action@v4.1.0

      - name: Docker Compose Setup
        uses: ndeloof/install-compose-action@v0.0.1

      - name: Create .env file
        run: |
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "DJANGO_DB_NAME=${{ secrets.DJANGO_DB_NAME }}" >> .env
          echo "DJANGO_DB_USER=${{ secrets.DJANGO_DB_USER }}" >> .env
          echo "DJANGO_DB_PASSWORD=${{ secrets.DJANGO_DB_PASSWORD }}" >> .env
          echo "DJANGO_DB_HOST=${{ secrets.DJANGO_DB_HOST }}" >> .env
          echo "DJANGO_DB_PORT=${{ secrets.DJANGO_DB_PORT }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env

      - name: Start up containers with docker compose
        run: docker-compose up -d

      - name: Run tests
        run: docker-compose exec task_manager pytest --cov=. --cov-report=term --cov-fail-under=90

      - name: Stop containers
        run: docker-compose down
