name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  black:
    name: Run Black
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run Black
        run: black .

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Setup Docker
        uses: docker/setup-docker-action@v4.1.0

      - name: Docker Compose Setup
        uses: ndeloof/install-compose-action@v0.0.1

      - name: Check .env exists
        run: ls -la .env

      - name: Start up containers with docker compose
        run: docker-compose up -d

      - name: Run migrations
        run: docker-compose exec web python manage.py migrate

      - name: Run tests
        run: docker-compose exec web pytest --cov=. --cov-report=term --cov-fail-under=90

      - name: Stop containers
        run: docker-compose down
