name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  black:
    name: Run Black
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run Black
        run: black .

  run-tests:
    name: Run pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python and Install Pytest
        uses: ./.github/actions/setup-python
        with:
          python-version: "3.12"
          dependencies: "poetry"

      - name: Install dependencies
        run: |
          poetry install

      - name: Create .env file from GitHub secrets
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "DJANGO_DB_NAME=${{ secrets.DJANGO_DB_NAME }}" >> .env
          echo "DJANGO_DB_USER=${{ secrets.DJANGO_DB_USER }}" >> .env
          echo "DJANGO_DB_PASSWORD=${{ secrets.DJANGO_DB_PASSWORD }}" >> .env
          echo "DJANGO_DB_HOST=${{ secrets.DJANGO_DB_HOST }}" >> .env
          echo "DJANGO_DB_PORT=${{ secrets.DJANGO_DB_PORT }}" >> .env

      - name: Test with pytest
        working-directory: ./task_manager
        run: poetry run pytest .
