name: CI

on:
  pull_request:
  push:

jobs:
  black:
    name: Run Black
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.12.3
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'
      - name: Black Check
        uses: jpetrucciani/black-check@24.10.0

  ruff:
    runs-on: ubuntu-latest
    name: Ruff Check
    steps:
      - name: Set up Python 3.12.3
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Ruff
        uses: wearerequired/lint-action@v2
        with:
          linter: ruff
          args: '. --config pyproject.toml'

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Setup Docker
        uses: docker/setup-docker-action@v4.1.0

      - name: Docker Compose Setup
        uses: ndeloof/install-compose-action@v0.0.1

      - name: Start up containers with docker compose
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DJANGO_DB_NAME: ${{ secrets.DJANGO_DB_NAME }}
          DJANGO_DB_USER: ${{ secrets.DJANGO_DB_USER }}
          DJANGO_DB_PASSWORD: ${{ secrets.DJANGO_DB_PASSWORD }}
          DJANGO_DB_HOST: localhost
          DJANGO_DB_PORT: 5432
          CELERY_BROKER_URL: ${{ secrets.CELERY_BROKER_URL }}
          CELERY_RESULT_BACKEND: ${{ secrets.CELERY_RESULT_BACKEND }}
          SEND_MAIL_API_URL: ${{ secrets.SEND_MAIL_API_URL }}
          SEND_MAIL_API_KEY: ${{ secrets.SEND_MAIL_API_KEY }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        run: docker-compose up -d

      - name: Run migrations
        run: docker-compose exec web python manage.py migrate

      - name: Run tests
        run: docker-compose exec web pytest --cov=. --cov-report=term --cov-fail-under=90

      - name: Stop containers
        run: docker-compose down